### PR TITLE
Fix detection of test/lint cancellation.

### LINKED ISSUE #45: After selecting 'cancel', lint and tests proceed anyway
(placeholder - I'll fill in a description and make a PR)

### PR DESCRIPTION
**Pull request by ceball**
Fixes #45

### CODE REVIEW

File: src/run.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ function runCellTests(app: JupyterFrontEnd, docManager: IDocumentManager): void
         buttons: [Dialog.cancelButton(), Dialog.okButton({ label: "Ok" })],
         title: "Run tests?",
     }).then((result) => {
-        if (result.button.label === "CANCEL") {
+        if (result.button.label === "Cancel") {
```
Comment (vidartf) [inline src/run.ts]: This could also just be `!result.button.accept`, to avoid relying on the label text value (probably not API stable).
